config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create] do
    member do
      get :confirm_email
      get :data
      get :home
    end

    resources :carts
    resources :tags
    resources :prefab_stores
    resources :prefab_items
  end

  resources :carts do
    resources :cart_items, only: [:new, :create, :destroy]
  end

  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'
  get '/auth/amazon/callback', to: 'sessions#amazon_signin'

  root "welcome#home"
end

app/models/prefab_item.rb
class PrefabItem < ApplicationRecord
    belongs_to :user
    has_many :cart_items
    has_many :carts, through: :cart_items
    has_many :prefab_item_tags
    has_many :tags, through: :prefab_item_tags

    validates :name, presence: true
    validates_uniqueness_of :name, scope: :user

    def name_and_tag_names
        "#{name} (#{self.tag_names.join(', ')})"
      end
  
    def tag_names
        tags ? tags.map {|tag| tag.name } : []
    end

    def total_spent
        cart_items.reduce(0) {|total, cart_item| total += cart_item.price }
    end
end

app/controllers/prefab_items_controller.rb
class PrefabItemsController < NestedResourcesController
  before_action {|c| c.session_guard c.this_user_nested? }
  before_action :load_prefab_item, only: [:show, :edit, :update, :destroy]
  before_action :load_tags, only: [:index, :new, :create, :edit, :update]

  def index
    @prefab_items = @user.prefab_items

    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: @prefab_items }
    end
  end

  def show
  end

  def new
    @prefab_item = PrefabItem.new
    @resource = @prefab_item
  end

  def edit
  end

  def create
    super 'prefab_item', prefab_item_params
  end

  def update
    super @resource, 'prefab_item', prefab_item_params
  end

  def destroy
    super @prefab_item, user_prefab_items_path
  end

  private

  def prefab_item_params
    params.require(:prefab_item).permit(:name, tag_ids: [])
  end

  def load_prefab_item
    @prefab_item = @user.prefab_items.find_by(id: params[:id])
    if !@prefab_item
      redirect_to user_prefab_items_path
    end
    @resource = @prefab_item
  end

  def load_tags
    @tags = @user.tags
  end
end

app/views/prefab_items/_form.html.erb
<%= render partial: 'shared/form_validation_errors_notice', locals: { resource: @resource } %>

<%= form_with scope: @resource, local: true, url: form_url, method: submit_method do |f| %>
  <%= wly_form_div self, 'wly_labeled_text_field', f, :name %>
  <%= wly_check_boxes_for @tags, :tag_ids, "Tags", f %>
  <%= f.submit %>
<% end %>

app/views/prefab_items/edit.html.erb
<h1>Edit Prefab Item!</h1>
<%= render partial: "form", locals: {form_url: user_prefab_item_path, submit_method: 'patch'} %>

app/views/prefab_items/new.html.erb
<h1>New Prefab Item!</h1>
<%= render partial: "form", locals: {form_url: user_prefab_items_path, submit_method: 'post'} %>

app/views/prefab_items/show.html.erb
<h1><%= @prefab_item.name %></h1>

<h3>Tags:</h3>
<% @prefab_item.tags.each do |tag| %>
    <%= link_to tag.name, user_tag_path(@user, tag) %>&nbsp
<% end %>

<h3>Cart Items:</h3>
<% if !@prefab_item.cart_items.empty? %>
    <% @prefab_item.cart_items.each do |cart_item| %>
        <%= "#{cart_item.note} | " if !cart_item.note.empty? %>
        <%= "[a/an #{@prefab_item.name}] | " %>
        $<%= cart_item.price %> | 
        <%= link_to 'Cart', user_cart_path(@user, cart_item.cart) %>
    <% end %>
    <br>
    <br>
    <strong>Total: $<%= @prefab_item.total_spent %></strong>
<% else %>
    None yet :(
<% end %>

<br>
<br>
<br>
<br>

<%= link_to 'Edit Prefab Item', edit_user_prefab_item_path(@user, @prefab_item) %>
<br>
<br>
Deleting this prefab item is irreversible.<br>
<%= link_to 'Delete this prefab item', user_prefab_item_path(@user, @prefab_item), method: 'delete' %>