config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create] do
    member do
      get :confirm_email
      get :data
      get :home
    end

    resources :carts
    resources :tags
    resources :prefab_stores
    resources :prefab_items
  end

  resources :carts do
    resources :cart_items, only: [:new, :create, :destroy]
  end

  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'
  get '/auth/amazon/callback', to: 'sessions#amazon_signin'

  root "welcome#home"
end

app/views/shared/_form_validation_errors_notice.html.erb
<div>
  <br>
  <% if resource.errors.any? %>
    There were validation errors. Please review and correct them :)
    <ul>
    <% resource.errors.full_messages.each do |full_message| %> 
      <li><%= full_message %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<% if logged_in? %>
  <span id="logo">BB</span>
  <%= link_to 'Home', home_user_path(@user) %>
  <%= link_to 'C', user_carts_path(@user)  %>
  <%= link_to 'S', user_prefab_stores_path(@user) %>
  <%= link_to 'I', user_prefab_items_path(@user), id: 'prefab-items-navbar-link' %>
  <%= link_to 'T', user_tags_path(@user), id: 'tags-navbar-link' %>
  <%= link_to 'Sign Out', signout_path %>
<% else %>
  <span id="logo">BIG BUDGET</span>
<% end %>

app/views/shared/_nested_resource.html.erb
<% edit_path_helper = "edit_user_" + resource_name + "_path" %>
<% delete_path_helper = "user_" + resource_name + "_path" %>
<% show_path_helper = "user_" + resource_name + "_path" %>

<div>
  <strong><%= nested_resource.name %></strong>
  <%= link_to 'Show', send(show_path_helper, @user, nested_resource) %>&nbsp
  <%= link_to 'Edit', send(edit_path_helper, @user, nested_resource) %>&nbsp
  <%= link_to 'Delete', send(delete_path_helper, @user, nested_resource), method: 'delete' %>
  <br>
  
  <%= render partial: "shared/nested_resource_attribute", collection: nested_resource.tags %>
</div>
<br>

app/views/shared/_nested_resource_attribute.html.erb
<span><%= nested_resource_attribute.name %>,&nbsp