config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create] do
    member do
      get :confirm_email
      get :data
      get :home
    end

    resources :carts
    resources :tags
    resources :prefab_stores
    resources :prefab_items
  end

  resources :carts do
    resources :cart_items, only: [:new, :create, :destroy]
  end

  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'
  get '/auth/amazon/callback', to: 'sessions#amazon_signin'

  root "welcome#home"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :user_tags
  has_many :users, through: :user_tags
  has_many :cart_store_tags
  has_many :cart_stores, through: :cart_store_tags
  has_many :cart_item_tags
  has_many :cart_items, through: :cart_item_tags
  has_many :prefab_item_tags
  has_many :prefab_items, through: :prefab_item_tags
  has_many :prefab_store_tags
  has_many :prefab_stores, through: :prefab_store_tags

  validates :name, presence: true

  def self.ten_most_popular
    (Tag.all.sort {|tag1, tag2| tag2.users.count - tag1.users.count }).slice(0, 10)
  end

  def all_cart_items
    if !@all_cart_items_memoized
      cart_items_through_prefab_items = prefab_items.collect do |prefab_item|
        prefab_item.cart_items
      end
      cart_items_through_prefab_items.flatten!

      @all_cart_items_memoized = (cart_items + cart_items_through_prefab_items).uniq
    end

    @all_cart_items_memoized
  end

  def carts
    if !@all_carts_memoized
      # all the carts of the cart items
      # + all the carts of the cart stores
      # uniq! the fuq out of that bitch
      cart_item_carts = all_cart_items.map do |cart_item|
        cart_item.cart
      end

      cart_store_carts = cart_stores.map do |cart_store|
        cart_store.cart
      end

      @all_carts_memoized = (cart_item_carts + cart_store_carts).uniq
    end

    @all_carts_memoized
  end

  
  def total_spent
    all_cart_items.reduce(0) do |dollars, cart_item| 
      dollars += cart_item.dollars
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < NestedResourcesController
  before_action {|c| c.session_guard c.this_user_nested? }
  before_action :load_user_tag, only: [:show, :edit, :update, :destroy]
  before_action :load_user_prefabs, only: [:new, :edit, :create, :update]
  before_action :load_user_tag_prefabs, only: [:show]
  

  def index
    @tags = @user.tags

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @tags }
    end
  end

  def show
  end

  def new
    @tag = Tag.new
    @resource = @tag
  end

  def edit
  end

  def create
    # does a tag by this name already exist?
    # if so, associate it with this user
    tp = tag_params
    if (@tag = Tag.find_by(name: tp[:name]))
      @tag.users << @user

      if tp[:prefab_store_ids]
        @tag.prefab_stores.concat(tp[:prefab_store_ids].map { |psi| PrefabStore.find(psi) })
      end

      if tp[:prefab_item_ids]
        @tag.prefab_items.concat(tp[:prefab_items_ids].map { |pii| PrefabItem.find(pii) })
      end
      
      if @tag.save
        redirect_to user_tag_path(@user, @tag)
      else
        @resource = @tag
        render :new
      end
    # if not, create it the usual way
    else
      super 'tag', tag_params
    end
  end

  def update
    super @resource, 'tag', tag_params
  end

  def destroy
    @tag.users = @tag.users.select {|u| u != @user }

    # if the tag has no users left, we can and should destroy it
    if @tag.users.empty?
      super @tag, user_tags_path
    # otherwise, we should just wipe all other memory of THIS user
    else
      @tag.prefab_stores = @tag.prefab_stores.select {|ps| ps.user != @user }
      @tag.prefab_items = @tag.prefab_items.select {|pi| pi.user != @user }

      redirect_to user_tags_path(@user)
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name, prefab_store_ids: [], prefab_item_ids: [])
  end

  def load_user_prefabs
    @prefab_stores = @user.prefab_stores
    @prefab_items = @user.prefab_items
  end

  def load_user_tag_prefabs
    @prefab_stores = @tag.prefab_stores.select {|ps| ps.user == @user }
    @prefab_items = @tag.prefab_items.select { |pi| pi.user == @user }
  end

  def load_user_tag
    @tag = @user.tags.find_by(id: params[:id])
    if !@tag
      redirect_to user_tags_path
    end
    @resource = @tag
  end
end

app/views/tags/_form.html.erb
<%= render partial: 'shared/form_validation_errors_notice', locals: { resource: @resource } %>

<%= form_with scope: @resource, local: true, url: form_url, method: submit_method do |f| %>
  <%= wly_form_div self, 'wly_labeled_text_field', f, :name %>
  <%= wly_check_boxes_for @prefab_stores, :prefab_store_ids, "Stores", f %>
  <%= wly_check_boxes_for @prefab_items, :prefab_item_ids, "Items", f %>
  <%= f.submit %>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag!</h1>
<%= render partial: "form", locals: {form_url: user_tag_path, submit_method: 'patch'} %>

app/views/tags/new.html.erb
<h1>New Tag!</h1>
<%= render partial: "form", locals: {form_url: user_tags_path, submit_method: 'post'} %>

app/views/tags/show.html.erb
<h1>'<%= @tag.name %>'</h1>

<h3>Prefab Stores:</h3>
<% if @prefab_stores.empty? %>
    None yet!
<% else %>
    <% @prefab_stores.each do |prefab_store| %>
        <%= link_to prefab_store.name, user_prefab_store_path(@user, prefab_store) %>
        <br>
    <% end %>
<% end %>

<h3>Prefab Items:</h3>
<% if @prefab_items.empty? %>
    None yet!
<% else %>
    <% @prefab_items.each do |prefab_item| %>
        <%= link_to prefab_item.name, user_prefab_item_path(@user, prefab_item) %>
        <br>
    <% end %>
<% end %>

<h3>Carts:</h3>
<% if @tag.carts.empty? %>
    None yet!
<% else %>
    <% @tag.carts.each do |cart| %>
        <%= link_to cart.note, user_cart_path(@user, cart) %>
        <br>
    <% end %>
<% end %>

<h3>Cart Items:</h3>
<% if @tag.all_cart_items.empty? %>
    None yet!
<% else %>
    <% @tag.all_cart_items.each do |cart_item| %>
        <strong>$<%= cart_item.price %></strong> | <%= link_to cart_item.description, user_cart_path(@user, cart_item.cart) %>
    <% end %>
<% end %>

<h3>Total Spent: $<%= @tag.total_spent %></h3>

<%= link_to "Edit Tag", edit_user_tag_path(@user, @tag) %>
<br>
<br>
Deleting a tag is irreversible. If you later remake the tag,
you will have to re-tag all the previously tagged things. So, please be sure 
you understand and accept this before you click here to <%= link_to "delete this tag", user_tag_path(@user, @tag), method: 'delete' %>.