config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create] do
    member do
      get :confirm_email
      get :data
      get :home
    end

    resources :carts
    resources :tags
    resources :prefab_stores
    resources :prefab_items
  end

  resources :carts do
    resources :cart_items, only: [:new, :create, :destroy]
  end

  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'
  get '/auth/amazon/callback', to: 'sessions#amazon_signin'

  root "welcome#home"
end

app/models/prefab_store.rb
class PrefabStore < ApplicationRecord
    belongs_to :user
    has_many :cart_stores
    has_many :carts, through: :cart_stores
    has_many :prefab_store_tags
    has_many :tags, through: :prefab_store_tags

    validates :name, presence: true
    validates_uniqueness_of :name, scope: :user

    def name_and_tag_names
      "#{name} (#{self.tag_names.join(', ')})"
    end

    def tag_names
        tags ? tags.map {|tag| tag.name } : []
    end

    def total_spent
        carts.reduce(0) {|dollars, cart| dollars += cart.total }
    end
end

app/controllers/prefab_stores_controller.rb
class PrefabStoresController < NestedResourcesController
  before_action {|c| c.session_guard c.this_user_nested? }
  before_action :load_prefab_store, only: [:show, :edit, :update, :destroy]
  before_action :load_tags, only: [:index, :new, :create, :edit, :update]

  def index
    @prefab_stores = @user.prefab_stores
  end

  def show
  end

  def new
    @prefab_store = PrefabStore.new
    @resource = @prefab_store
  end

  def edit
  end

  def create
    super 'prefab_store', prefab_store_params
  end

  def update
    super @resource, 'prefab_store', prefab_store_params
  end

  def destroy
    super @prefab_store, user_prefab_stores_path
  end

  private

  def prefab_store_params
    params.require(:prefab_store).permit(:name, tag_ids: [])
  end

  def load_prefab_store
    @prefab_store = @user.prefab_stores.find_by(id: params[:id])
    if !@prefab_store
      redirect_to user_prefab_stores_path
    end
    @resource = @prefab_store
  end

  def load_tags
    @tags = @user.tags
  end
end

app/views/prefab_stores/_form.html.erb
<%= render partial: 'shared/form_validation_errors_notice', locals: { resource: @resource } %>

<%= form_with scope: @resource, local: true, url: form_url, method: submit_method do |f| %>
  <%= wly_form_div self, 'wly_labeled_text_field', f, :name %>
  <%= wly_check_boxes_for @tags, :tag_ids, "Tags", f %>
  <%= f.submit %>
<% end %>

app/views/prefab_stores/edit.html.erb
<h1>Edit Prefab Store!</h1>
<%= render partial: "form", locals: {form_url: user_prefab_store_path, submit_method: 'patch'} %>

app/views/prefab_stores/index.html.erb
<h1>
  <%= @user.email %>'s Prefab Stores!
</h1>

<%= render partial: "shared/nested_resource", collection: @prefab_stores, locals: {resource_name: 'prefab_store'} %>

app/views/prefab_stores/new.html.erb
<h1>New Prefab Store!</h1>
<%= render partial: "form", locals: {form_url: user_prefab_stores_path, submit_method: 'post'} %>

app/views/prefab_stores/show.html.erb
<h1><%= @prefab_store.name %> | $<%= @prefab_store.total_spent %></h1>

Tags:<br>
<% @prefab_store.tags.each do |tag| %>
    <%= link_to tag.name, user_tag_path(@user, tag) %>&nbsp
<% end %>
<br>
<br>

Carts:<br>
<% @prefab_store.carts.each do |cart| %>
    <%= link_to cart.note, user_cart_path(@user, cart) %>
    <br>
    <%= cart.date %> | <strong>$<%= cart.total %></strong>
    <br>
    <br>
<%end %>

<%= link_to 'Edit Store', edit_user_prefab_store_path(@user, @prefab_store) %>
<br>
<br>
<br>
Deleting the store is irreversible. If you recreate it, you will have to manually re-associate any carts that were previously associated with it.
So before clicking <%= link_to 'delete store', user_prefab_store_path(@user, @prefab_store), method: 'delete' %>, please make sure that you really want to do this.